markdown: redcarpet
relative_permalinks: false

title: Vineyard
description: Vineyard, where the hosting is free and you get more than what you pay for.
url: https://vineyard.haus

exclude:
- Gemfile
- Gemfile.lock
- build
- vendor
